// just to basic lay out

const linksData = [
    {
        user: 1,
        catagory: 1,
        name: 'Boot Camp Login ',
        link: 'https://idp.bootcampspot.com/ui/?requestId=a529657e-536e-481e-a3a1-d915235a0379',
        favIcon: 'https://courses.bootcampspot.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 1,
        name: 'GitLab',
        link: 'https://umn.bootcampcontent.com/',
        favIcon: 'https://umn.bootcampcontent.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 1,
        name: 'GitHub',
        link: 'https://github.com/',
        favIcon: 'https://github.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 1,
        name: 'Stack Over Flow',
        link: 'https://stackoverflow.com/',
        favIcon: 'https://stackoverflow.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 1,
        name: 'FavIcon',
        link: 'https://www.favicon.cc/',
        favIcon: 'https://www.favicon.cc/favicon.ico',
    },
    {
        user: 1,
        catagory: 2,
        name: 'JQuery',
        link: 'https://jquery.com/',
        favIcon: 'https://jquery.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 2,
        name: 'Markdown Guide',
        link: 'https://www.markdownguide.org/',
        favIcon: 'https://www.markdownguide.org/favicon.ico',
    },
    {
        user: 1,
        catagory: 2,
        name: 'Google Fonts',
        link: 'https://fonts.google.com/',
        favIcon: 'https://www.gstatic.com/images/icons/material/apps/fonts/1x/catalog/v5/favicon.svg',
    },
    {
        user: 1,
        catagory: 2,
        name: 'Open Iconic',
        link: 'https://useiconic.com/open',
        favIcon: 'https://useiconic.com/favicon.png',
    },
    {
        user: 1,
        catagory: 2,
        name: 'BootStrap',
        link: 'https://getbootstrap.com/docs/5.1/getting-started/introduction/',
        favIcon: 'https://getbootstrap.com/docs/5.1/assets/img/favicons/favicon-32x32.png',
    },
    {
        user: 1,
        catagory: 2,
        name: 'Free Code Camp',
        link: 'https://www.freecodecamp.org/learn/',
        favIcon: 'https://www.freecodecamp.org/favicon-32x32.png',
    },
    {
        user: 1,
        catagory: 3,
        name: 'Generating SSH Key',
        link: 'https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 3,
        name: 'Checking SSH Keys',
        link: 'https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 3,
        name: '150+ Badges for Git hub',
        link: 'https://dev.to/envoy_/150-badges-for-github-pnk',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 3,
        name: 'Custom Badges',
        link: 'https://javascript.plainenglish.io/how-to-make-custom-language-badges-for-your-profile-using-shields-io-d2aeaf016b6b',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 3,
        name: 'Sheilds',
        link: 'http://shields.io',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 3,
        name: 'W3 Scools',
        link: 'https://www.w3schools.com',
        favIcon: 'https://www.w3schools.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 4,
        name: 'Ender 3',
        link: 'http://192.168.0.101/',
        favIcon: 'http://192.168.0.101/static/img/tentacle-32x32.png',
    },
    {
        user: 1,
        catagory: 4,
        name: 'Thingiverse',
        link: 'http://www.thingiverse.com',
        favIcon: 'http://www.thingiverse.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 4,
        name: 'Thangs',
        link: 'http://www.thangs.com',
        favIcon: 'http://www.thangs.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 4,
        name: '3D Printer Calibration',
        link: 'https://teachingtechyt.github.io/calibration.html#esteps',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 4,
        name: 'Use OctoPrint ',
        link: 'https://howchoo.com/g/ntg5yzg1odk/using-octoprint-with-the-creality-ender-3-3d-printer',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 5,
        name: 'Netflix',
        link: 'http://www.netflix.com',
        favIcon: 'http://www.netflix.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 5,
        name: 'Hulu',
        link: 'http://www.hulu.com',
        favIcon: 'http://www.hulu.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 5,
        name: 'Disney+',
        link: 'https://www.disneyplus.com/',
        favIcon: 'https://www.disneyplus.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 6,
        name: 'Pintrest',
        link: 'http://pintrest.com',
        favIcon: 'http://pintrest.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 6,
        name: 'Facebook',
        link: 'http://facebook.com',
        favIcon: 'http://facebook.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 6,
        name: 'Instagtam',
        link: 'http://instagram.com',
        favIcon: 'http://instagram.com/favicon.ico',
    },
    {
        user: 1,
        catagory: 6,
        name: 'Zoom',
        link: 'https://us05web.zoom.us/profile',
        favIcon: 'https://us05web.zoom.us/zoom.ico',
    },
    {
        user: 1,
        catagory: 1,
        name: ' ',
        link: '',
        favIcon: '',
    },
    {
        user: 1,
        catagory: 1,
        name: ' ',
        link: '',
        favIcon: '',
    },
    
]    